### ISSUE TITLE
Sporadic failure in test-plc-endpoints tests.

### ISSUE THREAD

**Issue by MatthewHink** [vapor-ware/synse-server#11]
## Description
Looks like this: https://circleci.com/gh/vapor-ware/synse-server/32

## Related Issues
- 

## Close Criteria
-

**Comment by MatthewHink** [comment]
Another one looks like this:
https://circleci.com/gh/vapor-ware/synse-server/33

**Comment by MatthewHink** [comment]
https://circleci.com/gh/vapor-ware/synse-server/34

**Comment by MatthewHink** [comment]
https://circleci.com/gh/vapor-ware/synse-server/35

It's almost like synse isn't fully up yet? A guess

**Comment by edaniszewski** [comment]
I thought thats what it looked like too at first, but then I saw that the wait for service readiness appeared to be fine
```
test-container-x64      | waiting for synse-test-container:5000
test-container-x64      | 
test-container-x64      | synse-test-container:5000 ready.
```

I ran the plc tests locally and after a few attempts saw what looks to be the same error (with the plc-emulator-tests suite). looking at the logs, it seems like there is an issue with the PLC bus comms - whether that be our code, some configuration, socat, a timing issue, something else -- I don't know, but I think thats where the issue lies

```
synse  | [2017-10-13 12:26:16,066] app:210 - =====================================
synse  | [2017-10-13 12:26:16,067] app:211 - Starting Synse Endpoint
synse  | [2017-10-13 12:26:16,068] app:212 - [2017-10-13 12:26:16.068274]
synse  | [2017-10-13 12:26:16,069] app:213 - Config default: /synse/default/default.json
synse  | [2017-10-13 12:26:16,070] app:214 - Config override: /synse/override
synse  | [2017-10-13 12:26:16,071] app:215 - cfg: {'cache_threshold': 500, 'devices': {u'plc': {u'config': {u'racks': [{u'hardware_type': u'emulator', u'lockfile': u'/tmp/Synse.lock', u'rack_id': u'rack_1', u'devices': [{u'time_slice': 75, u'bps': 115200, u'retry_limit': 3, u'timeout': 0.5, u'device_name': u'/dev/ttyVapor002'}]}]}}}, '_override': '/synse/override', 'scan_cache_file': u'/tmp/synse/cache.json', '_default': '/synse/default/default.json', 'cache_timeout': 600}
synse  | [2017-10-13 12:26:16,072] app:216 - =====================================
synse  | [2017-10-13 12:26:16,087] plc_bus:136 - Initialized DeviceBus with hardware: 32 device_name: /dev/ttyVapor002 speed: 115200 timeout: 0.5
synse  | [2017-10-13 12:26:16,092] plc_device:1158 - >>Scan: ['0x1', '0xa', '0x1', '0xff', '0x80', '0x78', '0x90', '0x4b', '0xff', '0xff', '0x44', '0xeb', '0x4']
synse  | [2017-10-13 12:26:16,596] plc_device:155 (ERROR) - Failed to scan all on PLC device registration.
synse  | [2017-10-13 12:26:16,596] plc_device:156 (ERROR) - Scan All: Error when scanning all boards (Scan command bus timeout.)
synse  | [2017-10-13 12:26:16,596] plc_device:155 - Failed to scan all on PLC device registration.
synse  | [2017-10-13 12:26:16,596] plc_device:156 - Scan All: Error when scanning all boards (Scan command bus timeout.)
Traceback (most recent call last):
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 153, in _get_board_records
    scan_response = self._scan_all(cmd)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 423, in _scan_all
    plc_rack = self._vapor_scan(request, bus)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 1163, in _vapor_scan
    expected_sequence=packet.sequence
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 448, in __init__
    super(DumpResponse, self).__init__(serial_reader=serial_reader, expected_sequence=expected_sequence)
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 268, in __init__
    raise BusTimeoutException('No response from bus.')
SynseException: Scan All: Error when scanning all boards (Scan command bus timeout.)
synse  | [2017-10-13 12:26:16,597] app:254 - Registered 1 Device(s)
synse  | [2017-10-13 12:26:16,597] app:256 - ... <PLCDevice (name: /dev/ttyVapor002, hardware: 32, boards: 0)>
synse  | [2017-10-13 12:26:16,598] app:258 - Endpoint Setup and Registration Complete
synse  | [2017-10-13 12:26:16,598] app:259 - ----------------------------------------
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xe82d40 pid: 27 (default app)
synse  | [2017-10-13 12:26:16,602] utils:61 - making response
Traceback (most recent call last):
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 153, in _get_board_records
    scan_response = self._scan_all(cmd)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 423, in _scan_all
    plc_rack = self._vapor_scan(request, bus)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 1163, in _vapor_scan
    expected_sequence=packet.sequence
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 448, in __init__
    super(DumpResponse, self).__init__(serial_reader=serial_reader, expected_sequence=expected_sequence)
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 268, in __init__
    raise BusTimeoutException('No response from bus.')
SynseException: Scan All: Error when scanning all boards (Scan command bus timeout.)
nginx  | 172.18.0.3 - - [13/Oct/2017:12:26:16 +0000] "GET /synse/version HTTP/1.1" 200 58 "-" "curl/7.47.0"
uwsgi  | synse-test-container:5000 [pid: 27] 172.18.0.3 [13/Oct/2017:12:26:16 +0000] GET /synse/version => HTTP/1.1 200 | 129 bytes in 4ms
synse  | [2017-10-13 12:26:16,726] utils:430 - getting device instance for board_id: 00000010
[2017-10-13 12:26:16,727] ERROR in app: Exception on /synse/1.4/read/thermistor/rack_1/10/01ff [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/synse/synse/blueprints/main_blueprint.py", line 345, in read_device
    device = get_device_instance(board_id)
  File "/synse/synse/utils.py", line 446, in get_device_instance
    'Board ID ({:08x}) not associated with any registered devicebus handler.'.format(board_id)
SynseException: Board ID (00000010) not associated with any registered devicebus handler.
```

here - for PLC we need to scan to figure out whats there, so before we start up the endpoint, we do the scan. we see that it fails with a bus timeout exception and only 1 PLC device is registered. I'll try and dig into this some more. 

the sporadic nature of this makes me thing that this is a timing/setup issue somewhere.

**Comment by MatthewHink** [comment]
Thanks for checking this out and getting a log.
I'm going to try bumping up the plc timeouts from .25 to .5 to see what happens.
I hit this a lot when trying to check in yesterday (well over half the time)

**Comment by edaniszewski** [comment]
its been hard to reproduce this on my machine, but it looks like this is being caused by an empty response to synse from the emulator on startup --

```
synse  | [2017-10-13 13:40:18,453] app:210 - =====================================
synse  | [2017-10-13 13:40:18,454] app:211 - Starting Synse Endpoint
synse  | [2017-10-13 13:40:18,455] app:212 - [2017-10-13 13:40:18.454940]
synse  | [2017-10-13 13:40:18,455] app:213 - Config default: /synse/default/default.json
synse  | [2017-10-13 13:40:18,455] app:214 - Config override: /synse/override
synse  | [2017-10-13 13:40:18,456] app:215 - cfg: {'cache_threshold': 500, 'devices': {u'plc': {u'config': {u'racks': [{u'hardware_type': u'emulator', u'lockfile': u'/tmp/Synse.lock', u'rack_id': u'rack_1', u'devices': [{u'time_slice': 75, u'bps': 115200, u'retry_limit': 3, u'timeout': 0.5, u'device_name': u'/dev/ttyVapor002'}]}]}}}, '_override': '/synse/override', 'scan_cache_file': u'/tmp/synse/cache.json', '_default': '/synse/default/default.json', 'cache_timeout': 600}
synse  | [2017-10-13 13:40:18,457] app:216 - =====================================
synse  | [2017-10-13 13:40:18,469] plc_bus:136 - Initialized DeviceBus with hardware: 32 device_name: /dev/ttyVapor002 speed: 115200 timeout: 0.5
synse  | [2017-10-13 13:40:18,471] plc_device:1158 - >>Scan: ['0x1', '0xa', '0x1', '0xff', '0x80', '0x78', '0x90', '0x4b', '0xff', '0xff', '0x44', '0xeb', '0x4']
synse  | [2017-10-13 13:40:18,974] plc_bus:268 - Failed to communicate on PLC bus!!
synse  | [2017-10-13 13:40:18,976] plc_bus:269 - ord() expected a character, but string of length 0 found
Traceback (most recent call last):
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 242, in __init__
    header = ord(serial_reader.read(1))
TypeError: ord() expected a character, but string of length 0 found
synse  | [2017-10-13 13:40:18,976] plc_bus:269 (ERROR) - ord() expected a character, but string of length 0 found
Traceback (most recent call last):
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 242, in __init__
    header = ord(serial_reader.read(1))
TypeError: ord() expected a character, but string of length 0 found
synse  | [2017-10-13 13:40:18,978] plc_device:155 - Failed to scan all on PLC device registration.
synse  | [2017-10-13 13:40:18,978] plc_device:155 (ERROR) - Failed to scan all on PLC device registration.
synse  | [2017-10-13 13:40:18,979] plc_device:156 - Scan All: Error when scanning all boards (Scan command bus timeout.)
Traceback (most recent call last):
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 153, in _get_board_records
    scan_response = self._scan_all(cmd)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 423, in _scan_all
    plc_rack = self._vapor_scan(request, bus)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 1163, in _vapor_scan
    expected_sequence=packet.sequence
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 450, in __init__
    super(DumpResponse, self).__init__(serial_reader=serial_reader, expected_sequence=expected_sequence)
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 270, in __init__
    raise BusTimeoutException('No response from bus.')
SynseException: Scan All: Error when scanning all boards (Scan command bus timeout.)
synse  | [2017-10-13 13:40:18,979] plc_device:156 (ERROR) - Scan All: Error when scanning all boards (Scan command bus timeout.)
Traceback (most recent call last):
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 153, in _get_board_records
    scan_response = self._scan_all(cmd)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 423, in _scan_all
    plc_rack = self._vapor_scan(request, bus)
  File "/synse/synse/devicebus/devices/plc/plc_device.py", line 1163, in _vapor_scan
    expected_sequence=packet.sequence
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 450, in __init__
    super(DumpResponse, self).__init__(serial_reader=serial_reader, expected_sequence=expected_sequence)
  File "/synse/synse/devicebus/devices/plc/plc_bus.py", line 270, in __init__
    raise BusTimeoutException('No response from bus.')
SynseException: Scan All: Error when scanning all boards (Scan command bus timeout.)
synse  | [2017-10-13 13:40:18,982] app:254 - Registered 1 Device(s)
synse  | [2017-10-13 13:40:18,982] app:256 - ... <PLCDevice (name: /dev/ttyVapor002, hardware: 32, boards: 0)>
synse  | [2017-10-13 13:40:18,983] app:258 - Endpoint Setup and Registration Complete
synse  | [2017-10-13 13:40:18,983] app:259 - ----------------------------------------
```

one thing we could do is add a short wait after starting up the emulators to give them enough time to start up, configure, and be ready by the time the synse application comes online. testing that will be hard because this behavior is sporadic, but I'll add it in and run tests on CI a bunch of times to see if I can get it to happen again.

**Comment by MatthewHink** [comment]
This is not perfect, but substantially better:
https://github.com/vapor-ware/synse-server/pull/12
