### ISSUE TITLE
synse server error when no reading returned from sdk

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-server#176]
this is for sdk 1.0

```
synse-server    | [2018-06-19 18:10:41 +0000] - (synse)[WARNING] read:84: Read for ipmi/ipmisim/cf5ca636df49458db117b2dd2e9fb1ec returned gRPC "no readings found". Will apply None as reading value. Note that this response might indicate plugin error/misconfiguration.
ipmi-plugin     | time="2018-06-19T18:10:41Z" level=debug msg="[grpc] read rpc request" request="rack:\"ipmi\" board:\"ipmisim\" device:\"cf5ca636df49458db117b2dd2e9fb1ec\" "
ipmi-plugin     | time="2018-06-19T18:10:41Z" level=error msg="[data manager] no readings found" id=ipmi-ipmisim-cf5ca636df49458db117b2dd2e9fb1ec
synse-server    | [2018-06-19 18:10:42 +0000] - (root)[ERROR] handlers:105: Traceback (most recent call last):
synse-server    |   File "/usr/local/lib/python3.6/site-packages/synse-2.1.0-py3.6.egg/synse/commands/read.py", line 41, in read
synse-server    |     read_data = _plugin.client.read(rack, board, device)
synse-server    |   File "/usr/local/lib/python3.6/site-packages/synse-2.1.0-py3.6.egg/synse/proto/client.py", line 188, in read
synse-server    |     resp = [r for r in self.grpc.Read(req, timeout=timeout)]
synse-server    |   File "/usr/local/lib/python3.6/site-packages/synse-2.1.0-py3.6.egg/synse/proto/client.py", line 188, in <listcomp>
synse-server    |     resp = [r for r in self.grpc.Read(req, timeout=timeout)]
synse-server    |   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 347, in __next__
synse-server    |     return self._next()
synse-server    |   File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 341, in _next
synse-server    |     raise self
synse-server    | grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.NOT_FOUND, no readings found for device: ipmi-ipmisim-cf5ca636df49458db117b2dd2e9fb1ec)>
synse-server    | 
synse-server    | During handling of the above exception, another exception occurred:
synse-server    | 
synse-server    | Traceback (most recent call last):
synse-server    |   File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 545, in _GetFieldByName
synse-server    |     return message_descriptor.fields_by_name[field_name]
synse-server    | KeyError: 'value'
synse-server    | 
synse-server    | During handling of the above exception, another exception occurred:
synse-server    | 
synse-server    | Traceback (most recent call last):
synse-server    |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 556, in handle_request
synse-server    |     response = await response
synse-server    |   File "/usr/local/lib/python3.6/site-packages/synse-2.1.0-py3.6.egg/synse/validate.py", line 85, in inner
synse-server    |     return await f(request, *args, **kwargs)
synse-server    |   File "/usr/local/lib/python3.6/site-packages/synse-2.1.0-py3.6.egg/synse/routes/core.py", line 72, in read_route
synse-server    |     response = await commands.read(rack, board, device)
synse-server    |   File "/usr/local/lib/python3.6/site-packages/synse-2.1.0-py3.6.egg/synse/commands/read.py", line 92, in read
synse-server    |     value='',
synse-server    |   File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 484, in init
synse-server    |     field = _GetFieldByName(message_descriptor, field_name)
synse-server    |   File "/usr/local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 548, in _GetFieldByName
synse-server    |     (message_descriptor.name, field_name))
synse-server    | ValueError: Protocol message Reading has no "value" field.
synse-server    | 
```

**Comment by edaniszewski** [comment]
also: 

```
➜ curl localhost:5000/synse/2.1/read/rack-1/vec/ecbb145965fd5e86fa7dee495ded6cab
{
  "kind":"boot_target",
  "data":{

  }
}
```

```
synse-server    | [2018-06-19 18:48:55 +0000] - (sanic.access)[INFO] server:325: "GET http://localhost:5000/synse/2.1/read/rack-1/vec/ecbb145965fd5e86fa7dee495ded6cab  200 44"
amt-plugin      | time="2018-06-19T18:48:55Z" level=debug msg="[grpc] read rpc request" request="rack:\"rack-1\" board:\"vec\" device:\"ecbb145965fd5e86fa7dee495ded6cab\" "
amt-plugin      | time="2018-06-19T18:48:55Z" level=error msg="[data manager] unable to read device" id=rack-1-vec-ecbb145965fd5e86fa7dee495ded6cab
```
